FROM 1panel/maxkb:latest
# 安装通道和缺失依赖
RUN pip3 install --target=/opt/py3/lib/python3.11/site-packages \
    channels==4.3.2 channels-redis==4.3.0 zhipuai -i https://pypi.tuna.tsinghua.edu.cn/simple
# 修复缺失文件
RUN mkdir -p /opt/maxkb-app/tmp \
    /opt/maxkb-app/apps/models_provider/impl/tencent_model_provider/credential \
    /opt/maxkb-app/apps/models_provider/impl/tencent_model_provider/model \
    /opt/maxkb-app/apps/models_provider/impl/azure_model_provider/icon && \
    touch /opt/maxkb-app/apps/models_provider/impl/tencent_model_provider/credential/stt.py && \
    echo -e "class TencentSTTModel: pass\nclass TencentSpeechToText: pass" > /opt/maxkb-app/apps/models_provider/impl/tencent_model_provider/model/stt.py && \
    touch /opt/maxkb-app/apps/models_provider/impl/azure_model_provider/icon/azure_icon_svg
# 替换前端
COPY ui/dist/admin /opt/maxkb-app/ui/dist/admin
